export enum SyntaxKind {
  SpaceToken = "SpaceToken",
  IdentifierToken = "IdentifierToken",
  NumberToken = "NumberToken",
  PlusToken = "PlusToken",
  MinusToken = "MinusToken",
  SlashToken = "SlashToken",
  StarToken = "StarToken",
  ColonToken = "ColonToken",
  OpenParenToken = "OpenParenToken",
  CloseParenToken = "CloseParenToken",
  Greater = "Greater",
  EOFToken = "EOFToken",
  BadToken = "BadToken",
  CellReference = "CellReference",
  RangeReference = "RangeReference",
  ParenthesizedExpression = "ParenthesizedExpression",
  UnaryExpression = "UnaryExpression",
  BinaryExpression = "BinaryExpression",
  ReferenceDeclaration = "ReferenceDeclaration",
}
