export enum SyntaxKind {
  SpaceToken = "SpaceToken",
  IdentifierToken = "IdentifierToken",
  NumberToken = "NumberToken",
  PlusToken = "PlusToken",
  MinusToken = "MinusToken",
  SlashToken = "SlashToken",
  StarToken = "StarToken",
  ColonToken = "ColonToken",
  OpenParenToken = "OpenParenToken",
  CloseParenToken = "CloseParenToken",
  GreaterToken = "GreaterToken",
  PointerToken = "PointerToken",
  EOFToken = "EOFToken",
  BadToken = "BadToken",
  NumberSyntax = "NumberSyntax",
  IdentifierSyntax = "IdentifierSyntax",
  RowSyntax = "RowSyntax",
  ColumnSyntax = "ColumnSyntax",
  CellSyntax = "CellSyntax",
  RangeSyntax = "RangeSyntax",
  ParenthesisSyntax = "ParenthesisSyntax",
  UnarySyntax = "UnarySyntax",
  BinarySyntax = "BinarySyntax",
  ReferenceSyntax = "ReferenceSyntax",
}
