Program ::= Statement+
Statement ::= Html | Math

Html ::= Tag

Tag ::= OpenTag | CloseTag | UniTag
OpenTag ::= LessThan Identifier GreaterThan
CloseTag ::= LessThan Division Identifier GreaterThan
UniTag ::= LessThan Identifier Attribute* Division GreaterThan
Attribute ::= Identifier (Equals String)?

Math ::= Expression

Expression ::= Parenthesis | Binary | Unary | Identifier | Number
Parenthesis ::= OpenParen Expression CloseParen
Binary ::= Expression Operator Expression
Unary ::= Operator Expression

String ::= Quote Character* Quote
Identifier ::= Letter+
Float ::= Integer (Dot Integer)?
Integer ::= Number+
Character ::= Letter | Number
Operator ::= Plus | Minus | Division | Multiplication | Power
Letter ::= LowerCaseLetter | UpperCaseLetter

LowerCaseLetter ::= "a" | "b" | "c" ...
UpperCaseLetter ::= "A" | "B" | "C" ...
Number ::= "0" | "1" | "2" | ... | "9"
Space ::= " " | "\t" | "\r" | "\n" | "\t"
Plus ::= "+"
Minus ::= "-"
Division ::= "/"
Multiplication ::= "*"
Power ::= "^"
Equals ::= "="
LessThan ::= "<"
GreaterThan ::= ">"
OpenParen ::= "("
CloseParen ::= ")"
Quote ::= "\""
Dot ::= "."
