export enum SyntaxNodeKind {
  NumberToken = "NumberToken",
  ColonToken = "ColonToken",
  OpenParenthesisToken = "OpenParenthesisToken",
  CloseParenthesisToken = "CloseParenthesisToken",
  DotToken = "DotToken",
  GreaterToken = "GreaterToken",
  HashToken = "HashToken",
  Program = "Program",
  CellAssignment = "CellAssignment",
  BinaryExpression = "BinaryExpression",
  UnaryExpression = "UnaryExpression",
  ParenthesizedExpression = "ParenthesizedExpression",
  RangeReference = "RangeReference",
  CellReference = "CellReference",
  IdentifierToken = "IdentifierToken",
  Expression = "Expression",
  EndOfFileToken = "EndOfFileToken",
  BadToken = "BadToken",
}
