export enum SyntaxKind {
  EndOfFileToken,
  NumberToken,
  ColonToken,
  OpenParenthesisToken,
  CloseParenthesisToken,
  DotToken,
  GreaterToken,
  HashToken,
  SyntaxBinaryExpression,
  Expression,
  IdentifierToken,
  BadToken,
  OpenBraceToken,
  CloseBraceToken,
  SyntaxCompilationUnit,
  SyntaxCellAssignment,
  SyntaxUnaryExpression,
  SyntaxParenthesis,
  SyntaxCellReference,
  SyntaxError,
  PlusToken,
  MinusToken,
  StarToken,
  SlashToken,
  HatToken,
  CommentTrivia,
  SpaceTrivia,
  ColonColonToken,
  LineBreakTrivia,
  QuoteToken,
  EqualsToken,
}

export type SyntaxUnaryOperatorKind = SyntaxKind.PlusToken | SyntaxKind.MinusToken;
export type SyntaxBinaryOperatorKind = SyntaxUnaryOperatorKind | SyntaxKind.SlashToken | SyntaxKind.StarToken | SyntaxKind.HatToken;
