export enum DiagnosticCode {
  EmptyProgram,
  BadTokenFound,
  TokenNotAMatch,
  MissingEvaluationMethod,
  CantDivideByZero,
  MissingOperatorKind,
  CircularDependency,
  MissingBindingMethod,
  CantUseAsAReference,
  CantFindReference,
  UsedBeforeItsDeclaration,
  WrongFloatingNumberFormat,
  CantCopyNode,
  HasNeverBeenAssigned,
}
