export enum DiagnosticCode {
  EmptyProgram,
  BadTokenFound,
  TokenNotAMatch,
  MissingEvaluationMethod,
  CantDivideByZero,
  MissingOperatorKind,
  CircularDependency,
  MissingBindingMethod,
  CantUseAsAReference,
  NotFound,
  UsedBeforeItsDeclaration,
  WrongFloatingNumberFormat,
  CantCopyNode,
  HasNeverBeenAssigned,
  DocumentDoesNotExist,
  NotARangeMember,
}
