export enum DiagnosticCode {
  SourceCodeIsEmpty,
  BadTokenFound,
  TokenNotAMatch,
  MissingMethod,
  CantDivideByZero,
  MissingOperatorKind,
  CircularDependency,
  CantUseAsAReference,
  NameNotFound,
  UsedBeforeItsDeclaration,
  WrongFloatingNumberFormat,
  NotARangeMember,
  CantWriteExpression,
  MissingSwitchSignMethod,
}
