export enum BoundKind {
  BoundBinaryExpression = "BoundBinaryExpression",
  BoundRangeReference = "BoundRangeReference",
  BoundCellReference = "BoundCellReference",
  BoundIdentifier = "BoundIdentifier",
  BoundNumber = "BoundNumber",
  BoundUnaryExpression = "BoundUnaryExpression",
  BoundCopyCell = "BoundCopyCell",
  IsStatement = "IsStatement",
  CopyStatement = "CopyStatement",
  BoundProgram = "BoundProgram",
  BoundIsStatement = "BoundIsStatement",
  BoundRowReference = "BoundRowReference",
  BoundColumnReference = "BoundColumnReference",
}
