export enum SyntaxNodeKind {
  EndOfFileToken = "EOF",
  NumberToken = "NumberToken",
  SingleQuoteToken = "SingleQuoteToken",
  ColonToken = "ColonToken",
  OpenParenthesisToken = "OpenParenthesisToken",
  CloseParenthesisToken = "CloseParenthesisToken",
  DotToken = "DotToken",
  GreaterToken = "GreaterToken",
  HashToken = "HashToken",
  BinaryExpression = "SyntaxBinaryExpression",
  IdentifierToken = "IdentifierToken",
  BadToken = "BadToken",
  EqualsToken = "EqualsToken",
  OpenBraceToken = "OpenBraceToken",
  CloseBraceToken = "CloseBraceToken",
  SyntaxCompilationUnit = "SyntaxCompilationUnit",
  SyntaxBlock = "SyntaxBlock",
  SyntaxCellAssignment = "SyntaxCellAssignment",
  SyntaxUnaryExpression = "SyntaxUnaryExpression",
  SyntaxParenthesis = "SyntaxParenthesizedExpression",
  SyntaxCellReference = "SyntaxCellReference",
  SyntaxExpression = "Expression",
}
