export enum SyntaxNodeKind {
  NumberToken = "NumberToken",
  ColonToken = "ColonToken",
  OpenParenthesisToken = "OpenParenthesisToken",
  CloseParenthesisToken = "CloseParenthesisToken",
  DotToken = "DotToken",
  GreaterToken = "GreaterToken",
  HashToken = "HashToken",
  CompilationUnit = "CompilationUnit",
  CellAssignment = "CellAssignment",
  BinaryExpression = "BinaryExpression",
  UnaryExpression = "UnaryExpression",
  ParenthesizedExpression = "ParenthesizedExpression",
  RangeReference = "RangeReference",
  CellReference = "CellReference",
  IdentifierToken = "IdentifierToken",
  Expression = "Expression",
  EndOfFileToken = "EndOfFileToken",
  BadToken = "BadToken",
  EqualsToken = "EqualsToken",
  FunctionExpression = "FunctionExpression",
  OpenBraceToken = "OpenBraceToken",
  CloseBraceToken = "CloseBraceToken",
  BlockStatements = "BlockStatements",
  BlockScope = "BlockScope",
}
