export enum SyntaxNodeKind {
    NumberToken = "NumberToken",
    ColonToken = "ColonToken",
    OpenParenthesisToken = "OpenParenthesisToken",
    CloseParenthesisToken = "CloseParenthesisToken",
    DotToken = "DotToken",
    GreaterToken = "GreaterToken",
    HashToken = "HashToken",
    BinaryExpression = "SyntaxBinaryExpression",
    IdentifierToken = "IdentifierToken",
    EndOfFileToken = "EndOfFileToken",
    BadToken = "BadToken",
    EqualsToken = "EqualsToken",
    OpenBraceToken = "OpenBraceToken",
    CloseBraceToken = "CloseBraceToken",
    SyntaxCompilationUnit = "SyntaxCompilationUnit",
    SyntaxBlock = "SyntaxBlock",
    SyntaxCellAssignment = "SyntaxCellAssignment",
    SyntaxUnaryExpression = "SyntaxUnaryExpression",
    SyntaxParenthesis = "SyntaxParenthesizedExpression",
    SyntaxCellReference = "SyntaxCellReference",
    SyntaxExpression = "SyntaxExpression",
    NoneToken = "NoneToken"
}
