export enum SyntaxKind {
  BadToken = "BadToken",
  SpaceToken = "SpaceToken",
  IndentifierToken = "IndentifierToken",
  NumberToken = "NumberToken",
  PlusToken = "PlusToken",
  MinusToken = "MinusToken",
  SlashToken = "SlashToken",
  StarToken = "StarToken",
  ColonToken = "ColonToken",
  OpenParenthesisToken = "OpenParenthesisToken",
  CloseParenthesisToken = "CloseParenthesisToken",
  GreaterToken = "GreaterToken",
  PointerToken = "PointerToken",

  EOFToken = "EOFToken",

  BadNode = "BadeNode",
  NumberNode = "NumberNode",
  IndentifierNode = "IndentifierNode",
  RowNode = "RowNode",
  ColumnNode = "ColumnNode",
  CellNode = "CellNode",
  RangeNode = "RangeNode",
  OpenParenthesisNode = "OpenParenthesisNode",
  UnaryNode = "UnaryNode",
  BinaryNode = "BinaryNode",
  ReferenceNode = "ReferenceNode",
}
