export enum DiagnosticKind {
  EmptyProgram = "EmptyProgram",
  BadTokenFound = "BadTokenFound",
  TokenNotAMatch = "TokenNotAMatch",
  MissingMethod = "MissingMethod",
  CantDivideByZero = "CantDivideByZero",
  MissingOperatorKind = "MissingOperatorKind",
  CircularDependency = "CircularDependency",
  CantUseAsAReference = "CantUseAsAReference",
  ReportUndefinedCell = "ReportUndefinedCell",
  BadFloatingPointNumber = "BadFloatingPointNumber",
  NotARangeMember = "NotARangeMember",
  GloballyNotAllowed = "GloballyNotAllowed",
  SwitchOperatorMethod = "SwitchOperatorMethod",
  CantCopy = "ReportCantCopy",
}
